recipes/Models/ErrorViewModel.cs
using System;

namespace recipes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

recipes/Models/Ingredient.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace recipes.Models
{
    public class Ingredient
    {
        public Guid id { get; set; }
        public Guid recipeId { get; set; }

        [Required(ErrorMessage = "Ingredient name is required.")]
        public string Name { get; set; }
        public string Quantity { get; set; }
    }
}

recipes/Models/Recipe.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace recipes.Models
{
    public class Recipe
    {
        [Display(Name = "Id")]
        public Guid id { get; set; }

        [Required(ErrorMessage = "Recipe name is required.")]
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

recipes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using recipes.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace recipes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

recipes/Controllers/IngredientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using recipes.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using recipes.Repositories;

namespace recipes.Controllers
{
    public class IngredientController : Controller
    {
        private readonly IngredientRepository _repo;

        public IngredientController(IngredientRepository repo)
        {
            _repo = repo;
        }
        // GET: Ingredient/GetAllIngredients    
        public ActionResult GetAllIngredients()
        {
            ModelState.Clear();
            return View(_repo.GetAllIngredients());
        }

        // GET: Ingredient/AddIngredient   
        public ActionResult AddIngredient()
        {
            return View();
        }

        // POST: Ingredient/AddIngredient/{id}
        [HttpPost]
        public ActionResult AddIngredient(Guid id, Ingredient ing)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ing.recipeId = id;
                    if (_repo.AddIngredient(ing))
                    {
                        ViewBag.Message = "Ingredient added successfully";
                        return RedirectToAction("GetIngredients", "Recipe", new { id = ing.recipeId });
                    }
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Ingredient/UpdateIngredient/{id}   
        public ActionResult UpdateIngredient(Guid id)
        {
            return View(_repo.GetAllIngredients().Find(Ing => Ing.id == id));
        }

        // POST: Ingredient/UpdateIngredient/{id}    
        [HttpPost]

        public ActionResult UpdateIngredient(Guid id, Ingredient obj)
        {
            try
            {
                _repo.UpdateIngredient(obj);
                return RedirectToAction("GetIngredients", "Recipe", new { id = obj.recipeId });
            }
            catch
            {
                return View();
            }
        }

        // DELETE: Ingredient/DeleteIngredient/{id}  
        public ActionResult DeleteIngredient(Guid id)
        {
            try
            {
                Ingredient ing = _repo.GetIngredient(id);
                if (_repo.DeleteIngredient(id))
                {
                    ViewBag.AlertMsg = "Ingredient deleted successfully";

                }
                return RedirectToAction("GetIngredients", "Recipe", new { id = ing.recipeId });
            }
            catch
            {
                return View();
            }
        }
    }
}

recipes/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using recipes.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using recipes.Repositories;

namespace recipes.Controllers
{
    public class RecipeController : Controller
    {
        private readonly RecipeRepository _repo;
        private readonly IngredientRepository _ingRepo;

        public RecipeController(RecipeRepository repo, IngredientRepository ingRepo)
        {
            _repo = repo;
            _ingRepo = ingRepo;
        }
        // GET: Recipe/GetAllRecipes    
        public ActionResult GetAllRecipes()
        {
            ModelState.Clear();
            return View(_repo.GetAllRecipes());
        }

        // GET: Recipe/{id}/GetIngredients    
        public ActionResult GetIngredients(Guid id)
        {
            ModelState.Clear();
            return View(_ingRepo.GetIngredientsByRecipeId(id));
        }

        // GET: Recipe/AddRecipe    
        public ActionResult AddRecipe()
        {
            return View();
        }

        // POST: Recipe/AddRecipe    
        [HttpPost]
        public ActionResult AddRecipe(Recipe rec)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_repo.AddRecipe(rec))
                    {
                        ViewBag.Message = "Recipe added successfully";
                        return RedirectToAction("GetAllRecipes");
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Recipe/UpdateRecipe/{id}   
        public ActionResult UpdateRecipe(Guid id)
        {
            return View(_repo.GetAllRecipes().Find(Rec => Rec.id == id));

        }

        // POST: Recipe/UpdateRecipe/{id}
        [HttpPost]
        public ActionResult UpdateRecipe(Guid id, Recipe obj)
        {
            try
            {
                _repo.UpdateRecipe(obj);
                return RedirectToAction("GetAllRecipes");
            }
            catch
            {
                return View();
            }
        }

        // DELETE: Recipe/DeleteRecipe/{id}  
        public ActionResult DeleteRecipe(Guid id)
        {
            try
            {
                if (_repo.DeleteRecipe(id))
                {
                    ViewBag.AlertMsg = "Recipe deleted successfully";

                }
                return RedirectToAction("GetAllRecipes");
            }
            catch
            {
                return View();
            }
        }
    }
}

recipes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

recipes/Views/Ingredient/AddIngredient.cshtml
@model recipes.Models.Ingredient

<h4>Ingredient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddIngredient" asp-route-id="@(Context.Request.Query["id"])">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Recipe" asp-action="GetIngredients" asp-route-id="@(Context.Request.Query["id"])">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

recipes/Views/Ingredient/DeleteIngredient.cshtml
@model recipes.Models.Ingredient

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ingredient</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.recipeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.recipeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="DeleteIngredient">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

recipes/Views/Ingredient/UpdateIngredient.cshtml
@model recipes.Models.Ingredient

<h4>Ingredient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateIngredient">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.id)
            @Html.HiddenFor(model => model.recipeId)
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Recipe" asp-action="GetIngredients" asp-route-id="@Model.recipeId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

recipes/Views/Recipe/AddRecipe.cshtml
@model recipes.Models.Recipe

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddRecipe">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

recipes/Views/Recipe/GetAllRecipes.cshtml
@model IEnumerable<recipes.Models.Recipe>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

recipes/Views/Recipe/GetIngredients.cshtml
@model IEnumerable<recipes.Models.Ingredient>

<p>
    <a asp-controller="Ingredient" asp-action="AddIngredient" asp-route-id="@(Context.Request.Query["id"])">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.ActionLink("Edit", "UpdateIngredient", "Ingredient", new { id = item.id }) |
                @Html.ActionLink("Delete", "DeleteIngredient", "Ingredient", new { id = item.id })
            </td>
        </tr>
}
    </tbody>
</table>

recipes/Views/Recipe/UpdateRecipe.cshtml
@model recipes.Models.Recipe

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateRecipe">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model => model.id)
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAllRecipes">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

recipes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - recipes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="GetAllRecipes">Recipe List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Recipes
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>